version: "3.8"

volumes:
  db_storage:
  n8n_storage:

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - WEBHOOK_URL=""
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=abcd
    ports:
      - 127.0.0.1:5678:5678
    volumes:
      - ./data:/home/node/.n8n
